[config]
broker = '127.0.0.1'
port = 1883
topic-root = 'carpark'
topic-qualifier = 'controller'
name = 'display'
location = 'Moondalup City Square Parking'
total-spaces = 192
total-cars = 0
# TODO: finish this section of with relevant data maybe?