[config]
broker = '127.0.0.1'
port = 1883
topic-root = 'carpark'
topic-qualifier = 'controller'
name = 'parking-lot'
location = 'Moondalup City Square Parking'
total-spaces = 192
total-cars = 0
temperature = 0


